//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingreso
    {
        public int id { get; set; }
        public string anio { get; set; }
        public string trimestre { get; set; }
        public string proveedor { get; set; }
        public string segmento { get; set; }
        public string terminal { get; set; }
        public string ingresos { get; set; }
    }
}
